---
version: 2.1
jobs:
  xyzzy:
    docker:
      - image: cimg/node:22.4.1
    steps:
      - checkout
      - run: node --version
  print-a-message:
    docker:
      - image: cimg/base:2022.03
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>
workflow:
  plugh:
    jobs:
      - xyzzy
  my-workflow:
    jobs:
      - print-a-message:
          message: Hello!