---
version: 2.1
workflows:
  plugh:
    jobs:
      - test
jobs:
  test:
    docker:
      # Found on CircleCI website
      - image: cimg/node:22.4.1
    environment:
      BAZ: "defined at job level"
    steps:
      - checkout
      - run:
          name: Define env var at runtime
          command: |
            echo 'export FOO="Defined at runtime"' >> $BASH_ENV
            source $BASH_ENV
            echo "Value is ${FOO}"
      - run:
          name: Define env var at job invoke time
          command: echo "Value is ${BAR}"
          environment:
            BAR: "Defined at invoke time"
      - run:
          name: Display job-wide env var
          command: echo "My value is $BAZ"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: run tests
          command: npm run test

